pipeline {
    agent any
    
    environment {
        IMAGE_NAME = 'sicei'
        CONTAINER_NAME = 'sicei'
        TAG = "${BUILD_ID}"
    }
    
    stages {
        stage('Build') {
            steps {
                dir('sicei') {
                    bat "echo Construyendo la imagen Docker con tag: %TAG%"
                    bat "docker build -t ${IMAGE_NAME}:${TAG} ."
                }
            }
        }
        
     stage('Deploy') {
    steps {
        bat '''
            echo Deteniendo y eliminando el contenedor anterior si existe...

            set CONTAINER_ID=
            for /f "tokens=*" %%i in ('docker ps -q --filter "name=%CONTAINER_NAME%"') do (
                set CONTAINER_ID=%%i
            )
            if defined CONTAINER_ID (
                docker stop %CONTAINER_ID%
            ) else (
                echo No se encontraron contenedores en ejecución.
            )

            set CONTAINER_ID=
            for /f "tokens=*" %%i in ('docker ps -a -q --filter "name=%CONTAINER_NAME%"') do (
                set CONTAINER_ID=%%i
            )
            if defined CONTAINER_ID (
                docker rm %CONTAINER_ID%
            ) else (
                echo No se encontraron contenedores detenidos para eliminar.
            )
        '''

        bat "echo Desplegando la nueva imagen..."
        bat "docker run -d -p 3000:3000 --name %CONTAINER_NAME% %IMAGE_NAME%:%TAG%"

        echo "Proceso completado. Imagen: %IMAGE_NAME%:%TAG% en ejecución."
    }
}

    }
}